export const testimonialsData = [
  {
    id: 1,
    name: "Santu",
    role: "Content Creator & YouTuber",
    text: "Naan KV Media Works kuda work panna start pannirken, after that my content quality completely changed. They understand exactly what I need and deliver every time. Best editing team I've worked with, honestly no regrets!",
    rating: 5,
  },
  {
    id: 2,
    name: "Beardo Team",
    role: "Brand Marketing, Beardo",
    text: "KV Media Works handles our YouTube content with incredible quality. The long-form edits are cinematic and keep our audience hooked throughout. Super professional team to work with, always delivering on time.",
    rating: 5,
  },
  {
    id: 3,
    name: "Melby",
    role: "Content Creator",
    text: "Editing quality top-notch ah iruku, every video they deliver feels premium. They understand the vibe I want and always nail it. Fast turnaround and creative inputs are a big plus. Love working with them!",
    rating: 5,
  },
  {
    id: 4,
    name: "Bolt Digitech",
    role: "Digital Marketing Agency",
    text: "We outsource all our client video projects to KV Media Works. Their consistency and quality across short-form and corporate videos is outstanding. Reliable partner for any agency looking for top editing work.",
    rating: 5,
  },
  {
    id: 5,
    name: "Botfolio",
    role: "Tech Startup",
    text: "Our product demo and corporate videos were done by KV Media Works. Clean, professional, and exactly what we needed to showcase our platform. Highly recommended for any startup needing quality video content!",
    rating: 5,
  },
  {
    id: 6,
    name: "CookIT",
    role: "Food Tech Brand",
    text: "KV Media Works created amazing promotional videos for our platform. They captured the energy of our brand perfectly. The edits are always on point and delivered on time. Great team to collaborate with!",
    rating: 5,
  },
  {
    id: 7,
    name: "InkCharts",
    role: "Content Brand",
    text: "InkCharts ku short-form reels and YouTube content ellam KV Media Works than handle panraanga. Their turnaround time is fast and quality is always on point. Nalla creative team, easy to work with. Definitely recommend!",
    rating: 5,
  },
];
